# Generated by Django 3.0.2 on 2020-12-28 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tube_extension', '0002_video_durations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='durations',
        ),
        migrations.RemoveField(
            model_name='video',
            name='link',
        ),
    ]
